### ISSUE TITLE
 DataCollectorFiles.rar is faulty

### ISSUE THREAD

**Issue by dvukovic** [niriho/ESP32_SDS011#1]
WinRAR  states  "The archive is either in unknown format or damaged"

**Comment by niriho** [comment]
Hi,
I downloaded the file and extracted it with winrar with no issues :)
Might be an antivirus thing.
You can get the file in the hackaday I've created [here](https://hackaday.io/project/167370-air-pollution-monitoring-project) and I've also compressed the file into zip and uploaded it as well.
Let me know if you are still having an issue.

Thanks!

**Comment by dvukovic** [comment]
Still fails.

**Comment by dvukovic** [comment]
May I ask you to email them to me directly.

**Comment by niriho** [comment]
Of Course, with pleasure, please send me your email.

**Comment by dvukovic** [comment]
donvukovic@gmail.com

**Comment by niriho** [comment]
Sent, let me know if you didnt get it or if you have any issues.

**Comment by dvukovic** [comment]
Got the zip file. Everything looks good.
Why not post that zip file on git ?
